### PR TITLE
Newsletter

### PR DESCRIPTION
**Pull request by rakaar**
Screenshot from 2019-12-18 20-59-17
Screenshot from 2019-12-18 20-59-08
Screenshot from 2019-12-18 20-59-04
Screenshot from 2019-12-18 20-58-58

### CODE REVIEW

**Comment by thealphadollar** [comment]
@rakaar Please update @ajajaj2807 with what all you have missed in this and he'll work on them. I could see two changes:
- Sharing elements in mobile.
- A hovering subscribe instead of a button.

**Comment by thealphadollar** [comment]
@rakaar Please update me regarding what needs to be supplied from the backend for the html. And let's get live with this.

**Comment by rakaar** [comment]
@thealphadollar , all we need is HTML as you planned. To get it 
- Go to `/dynamic templates` in sendgrid
- Click on  settings like button of each newsletter
- click on export as html
- a text file will be downoaded. It contains html with css

*To get it live we need some good design changes. I will try to get done soon or get it done  by someone. Consider by end of this weekend*

**Review by thealphadollar — CHANGES_REQUESTED** [review]
@rakaar This looks amazing. Now what we need is that from the backend we get the HTML content as text alongside other information about the newsletter. Please implement all the design changes you want to before this.

We need this running by the weekend.

cc/ @mukul-mehta

**Pull request merged**
