### PR TITLE
Newsletter design is made

### PR DESCRIPTION
**Pull request by rakaar**
Basic newsletter design is made with harcoded content
Screenshot from 2020-01-12 12-11-32

Things to be done:

- [x] Integrate with CMS API once it is working

- [ ] Add comments through DISCUS or facebook comments pluggin or anyother other comment service

- [ ] Furthur design changes in the reading page

### CODE REVIEW

**Comment by thealphadollar** [comment]
The width of the content area should be reduced, but wait for a design from the design team.

**Comment by rakaar** [comment]
@thealphadollar  , this is the design given by design team
82052749_467690380820868_4731503592962260992_n

Ya reducing width makes it look better. this is at width: 60%
Screenshot from 2020-01-12 12-29-05

**Comment by thealphadollar** [comment]
Please make the hard coded design same as the one given except the navbar
and footer. We will keep that same for a while and use the subscribe and
share design as we have for newsletter.

Please involve Rashil also in this.

**Comment by thealphadollar** [comment]
@rashil2000 Hey, can you please add a new screenshot as well?

**Comment by rashil2000** [comment]
[IIT Tech Ambit - Google Chrome 2020-01-13 19-41-07.zip](https://github.com/iit-technology-ambit/Apsara2.0/files/4054217/IIT.Tech.Ambit.-.Google.Chrome.2020-01-13.19-41-07.zip)

Was having some trouble uploading the video. I've compressed it here.

**Comment by thealphadollar** [comment]
@rakaar @rashil2000 Please add screenshots and GIFs.

**Comment by rashil2000** [comment]
Desktop 2020 03 25 - 14 25 28 04_1
The gif is choppy because of compression.

**Comment by rakaar** [comment]
Awesome @rashil2000  :heart_eyes:  :heart_eyes: 
Once before merging the request(which will be done after uploading data in CMS is completed)
Please delete the test comments !
@thealphadollar

**Comment by rashil2000** [comment]
@rakaar Sure, just remind me when you're finally merging.

**Comment by thealphadollar** [comment]
@rakaar @rashil2000 Looks really good to me. Please oversee the upload of articles to CMS and thereafter, merge the same :D

**Pull request merged**
