### PR TITLE
Image to appear in link when shared on social media

### LINKED ISSUE #5: Picture not showing in Link
Whenever shared anywhere, it shows description and author but not the pic

### PR DESCRIPTION
**Pull request by rakaar**
In the tags the images refered to icon.png which wasn't there at all. So, downloaded a new pic from facebook profile pics, and named it as icon.jpg and changed accordingly in the meta tags. I believe this should work also seen the same thing [here](https://css-tricks.com/essential-meta-tags-social-media/)

fixes #5

### CODE REVIEW

**Review by thealphadollar — CHANGES_REQUESTED** [review]
The `icon.jpg` you've added is the past logo. Please update it to the latest one. And try it once by hosting it using ngrok.

Rest everything looks good to me, thank you for the contribution.

**Comment by rakaar** [comment]
@thealphadollar , I chose the logo because I felt that would look good when the link is shared, as it does not have a plain background. Okay will update with the latest as per the current facebook profile pic.

**Comment by thealphadollar** [comment]
Please update it.

**Comment by rakaar** [comment]
We cannot test it with ngrok. I think deployment is the only way to check.

**Review by thealphadollar — APPROVED** [review]
LGTM.

**Pull request merged**
